services:
  rahat_db:
    image: postgres:14
    restart: unless-stopped
    container_name: "rahat_db"
    environment:
      POSTGRES_PASSWORD: "rahat"
      POSTGRES_USER: "postgres"
      POSTGRES_MULTIPLE_DATABASES: core,project1
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./vol/rahat_db:/var/lib/postgresql/data
    # ports:
      # - 5432:5432
    network_mode: "host"

  rahat_redis:
    container_name: rahat_redis
    image: redis:6.2.12
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --requirepass rahat --maxmemory-policy noeviction
    volumes:
      - ./vol/rahat_redis:/data
    # ports:
      # - 6379:6379
    network_mode: "host"

  rahat_platform:
    image: esatya/rahat-platform-rahat:dev
    container_name: rahat_platform
    restart: unless-stopped
    env_file:
      - .env.platform
    # ports:
      # - 3333:3333
    network_mode: "host"

  rahat_beneficiary:
    image:  esatya/rahat-platform-beneficiary:dev
    container_name: rahat_beneficiary
    restart: unless-stopped
    env_file:
      - .env.platform
    network_mode: "host"

  rahat_ui:
    image:  esatya/rahat-ui:dev-local-setup
    container_name: rahat_ui
    restart: unless-stopped
    env_file:
      - .env.rahat-ui
    # ports:
      # - 3000:3000
    network_mode: "host"
